
#ifndef COMMAND_RESTART_BOARD
#define COMMAND_RESTART_BOARD "RESTART_BOARD"
#endif

#ifndef COMMAND_START_MICROPHONE
#define COMMAND_START_MICROPHONE "START_MICROPHONE"
#endif

#ifndef COMMAND_STOP_MICROPHONE
#define COMMAND_STOP_MICROPHONE "STOP_MICROPHONE"
#endif

#ifndef COMMAND_START_CAMERA
#define COMMAND_START_CAMERA "START_CAMERA"
#endif

#ifndef COMMAND_STOP_CAMERA
#define COMMAND_STOP_CAMERA "STOP_CAMERA"
#endif

#ifndef COMMAND_TAKE_PHOTO
#define COMMAND_TAKE_PHOTO "TAKE_PHOTO"
#endif
